version: '3.8'

services:
  springboot-app1:
    build: .
    container_name: springboot-app1
    ports:
      - "8081:8080"
    networks:
      - app-network

  springboot-app2:
      build: .
      container_name: springboot-app2
      ports:
        - "8082:8080"
      networks:
        - app-network

  nginx:
    image: nginx:stable-alpine
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - springboot-app1
      - springboot-app2
    networks:
      - app-network

networks:
  app-network:
    driver: bridge